# Generated by Django 5.2.5 on 2025-10-11 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas')),
                ('descripcion', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('tipo_motor', models.CharField(blank=True, max_length=50)),
                ('años_fabricacion', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('kilometraje', models.IntegerField()),
                ('km_por_litro', models.FloatField()),
                ('año', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autos')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DamianApp.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DamianApp.modelo')),
            ],
            options={
                'db_table': 'auto',
            },
        ),
    ]
